name: Update Blog Index

on:
  push:
    paths:
      - "posts/**"  # Trigger nur bei Änderungen im posts/-Ordner

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test Minimal Run
        run: |
          echo "Hallo Stefan, du torkelnder YAML-Tollpatsch!" > test.txt
          echo "Wenn das hier geht, mecker nicht mehr über Zeile 19." >> test.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add test.txt
          git commit -m "Added a test file"
          git push
