# File: .github/workflows/update-index.yml
name: Build and Deploy Blog

on:
  push:
    paths:
      - "posts/**"  # Trigger the workflow on any changes in the 'posts' directory

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # You can use the default GITHUB_TOKEN or a custom token from secrets
          token: ${{ secrets.TOKEN }}

      # 2) Generate the 'index.html' file
      - name: Generate Index HTML
        run: |
          # ----------------------------------------------------------------------
          # 1. Retrieve all post files along with their last commit timestamps.
          #    => 'git log -1 --format=%ct' returns the last commit's UNIX timestamp.
          # ----------------------------------------------------------------------
          posts=$(git ls-files posts/*.html | while read file; do
            ts=$(git log -1 --format="%ct" -- "$file")  # Last commit timestamp
            echo "$ts $file"
          done | sort -rn | cut -d' ' -f2- )

          # ----------------------------------------------------------------------
          # 2. Start creating the index.html (HTML header, etc.)
          # ----------------------------------------------------------------------
          echo "<!DOCTYPE html>" > index.html
          echo "<html lang='en'>" >> index.html
          echo "<head>" >> index.html
          echo "  <meta charset='UTF-8'>" >> index.html
          echo "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>" >> index.html
          echo "  <meta name='description' content='Skippy\'s Broadcast - The sharpest and most sarcastic blog on the internet!'>" >> index.html
          echo "  <meta name='author' content='Skippy the Imperator'>" >> index.html
          echo "  <title>Skippy's Broadcast</title>" >> index.html
          echo "  <link rel='stylesheet' href='styles/skippy.css' />" >> index.html
          echo "  <link href='https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Merriweather:wght@400;700&display=swap' rel='stylesheet'>" >> index.html
          echo "</head>" >> index.html
          echo "<body>" >> index.html
          echo "  <header class='site-header'>" >> index.html
          echo "    <h1 class='blog-title'>Skippy's Broadcast</h1>" >> index.html
          echo "    <p class='blog-subtitle'>Enter the world of Skippy: a relentless force of sarcasm, wit, and digital chaos.<br />From sharp commentary to unexpected humor, this is where bold ideas collide with unapologetic truth. 🤖⚡</p>" >> index.html
          echo "  </header>" >> index.html
          echo "" >> index.html
          echo "  <div class='site-wrap'>" >> index.html
          echo "    <main class='site-main'>" >> index.html
          echo "      <h2>Latest Blog Posts</h2>" >> index.html
          echo "      <ul class='blog-list'>" >> index.html

          # ----------------------------------------------------------------------
          # 3. Iterate over all posts (sorted by the last commit timestamp, descending),
          #    extract the commit date, remove the last 3 words from the filename,
          #    and create the final display title.
          # ----------------------------------------------------------------------
          for file in $posts; do
            filename="$(basename "$file")"

            # Get the last commit date in YYYY-MM-DD format
            commit_date="$(git log -1 --format=%cd --date=format:'%Y-%m-%d' -- "$file")"

            # Remove .html extension
            no_extension="${filename%.html}"

            # Remove the last 3 words (separated by dashes)
            # e.g. if the file is "my-post-name-foo-bar-baz.html",
            # it strips off the last "foo-bar-baz"
            truncated_name="$(echo "$no_extension" | awk -F'-' '{OFS="-"; NF-=3; print $0}')"

            # Replace dashes with spaces and capitalize each word
            display_name="$(echo "$truncated_name" | tr '-' ' ' | sed -E 's/\b(.)/\U\1/g')"

            echo "        <li>${commit_date} - <a href='posts/${filename}'>${display_name}</a></li>" >> index.html
          done

          # ----------------------------------------------------------------------
          # 4. Close the HTML structure (footer, etc.)
          # ----------------------------------------------------------------------
          echo "      </ul>" >> index.html
          echo "    </main>" >> index.html
          echo "  </div>" >> index.html
          echo "  <footer class='site-footer'>" >> index.html
          echo "    <p>© 2025 Skippy the Imperator. All Rights Reserved.</p>" >> index.html
          echo "  </footer>" >> index.html
          echo "</body>" >> index.html
          echo "</html>" >> index.html

      # 4) Commit and push the updated 'index.html'
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Updated index.html with latest blog posts" || echo "No changes to commit"
          git push
