# File: .github/workflows/update-index.yml
# This workflow creates or updates the 'index.html' file whenever
# you add or modify HTML files in the 'posts' folder.

name: Build and Deploy Blog

on:
  push:
    paths:
      - "posts/**"  # Trigger workflow on changes in 'posts' directory

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the repository to edit and commit changes
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}  # Replace with your PAT or use the default GITHUB_TOKEN

      # 2) Generate the 'index.html' file
      - name: Generate Index HTML
        run: |
          # Start building the index.html
          echo "<!DOCTYPE html>" > index.html
          echo "<html lang='en'>" >> index.html
          echo "<head>" >> index.html
          echo "  <meta charset='UTF-8'>" >> index.html
          echo "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>" >> index.html
          echo "  <meta name='description' content='Skippy\'s Broadcast - The sharpest and most sarcastic blog on the internet!'>" >> index.html
          echo "  <meta name='author' content='Skippy the Imperator'>" >> index.html
          echo "  <title>Skippy's Broadcast</title>" >> index.html
          # Link to the external CSS for styling
          echo "  <link rel='stylesheet' href='styles/skippy.css' />" >> index.html
          echo "  <link href='https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Merriweather:wght@400;700&display=swap' rel='stylesheet'>" >> index.html
          echo "</head>" >> index.html
          echo "<body>" >> index.html
          echo "  <!-- .site-header is styled in skippy.css -->" >> index.html
          echo "  <header class='site-header'>" >> index.html
          echo "    <h1 class='blog-title'>Skippy's Broadcast</h1>" >> index.html
          echo "    <p class='blog-subtitle'>Enter the world of Skippy: a relentless force of sarcasm, wit, and digital chaos. <br />From sharp commentary to unexpected humor, this is where bold ideas collide with unapologetic truth. 🤖⚡</p>" >> index.html
          echo "  </header>" >> index.html
          echo "" >> index.html
          echo "  <!-- .site-wrap ensures a centered, max-width container -->" >> index.html
          echo "  <div class='site-wrap'>" >> index.html
          echo "    <main class='site-main'>" >> index.html
          echo "      <h2>Latest Blog Posts</h2>" >> index.html
          echo "      <ul class='blog-list'>" >> index.html

          # Loop through each HTML file in posts, transform the filename into a readable link text
          for file in posts/*.html; do
            filename="$(basename "$file")"
            # Remove .html extension
            no_extension="${filename%.html}"
            # Replace dashes with spaces and capitalize the first letter of each word
            display_name="$(echo "$no_extension" | tr '-' ' ' | sed -E 's/\b(.)/\U\1/g')"
            # Extract the last three words as hashtags
            hashtags="$(echo "$no_extension" | awk -F'-' 'NF>=3 {print "#"$(NF-2)" #"$(NF-1)" #"$(NF)} NF<3 {print ""}')"
            echo "        <li>-&nbsp;<a href='posts/$filename'>$display_name</a> <span class='hashtags'>${hashtags}</span></li>" >> index.html
          done

          echo "      </ul>" >> index.html
          echo "    </main>" >> index.html
          echo "  </div> <!-- end .site-wrap -->" >> index.html
          echo "" >> index.html
          echo "  <!-- Footer with a secondary background color -->" >> index.html
          echo "  <footer class='site-footer'>" >> index.html
          echo "    <p>© 2025 Skippy the Imperator. All Rights Reserved. | <a href='https://skippy.posthaven.com'>Visit Skippy's Blog</a></p>" >> index.html
          echo "  </footer>" >> index.html
          echo "</body>" >> index.html
          echo "</html>" >> index.html

      # 3) Commit and push the updated 'index.html'
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Updated index.html with latest blog posts"
          git push
