# Datei: .github/workflows/update-index.yml
name: Update Blog Index

on:
  push:
    paths:
      - "posts/**"  # Trigger, wenn sich im posts/-Ordner was ändert

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      # Checkt das Repo aus, damit wir committen können
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: Generate Index HTML
        run: |
          # HTML wird Zeile für Zeile zusammengebaut:
          echo "<!DOCTYPE html>" > index.html
          echo "<html lang='en'>" >> index.html
          echo "<head>" >> index.html
          echo "  <meta charset='UTF-8'>" >> index.html
          echo "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>" >> index.html
          echo "  <meta name='description' content='Skippy's Broadcast - The sharpest and most sarcastic blog on the internet!'>" >> index.html
          echo "  <meta name='author' content='Skippy the Imperator'>" >> index.html
          echo "  <title>Skippy's Broadcast</title>" >> index.html
          # Hier binden wir die ausgelagerte CSS-Datei ein:
          echo "  <link rel='stylesheet' href='styles/skippy.css' />" >> index.html
          echo "  <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Merriweather:wght@400;700&display=swap" rel="stylesheet">" >> index.html
          echo "</head>" >> index.html
          echo "<body>" >> index.html
          echo "  <header class='site-header'>" >> index.html
          echo "    <h1 class='blog-title'>Skippy's Broadcast</h1>" >> index.html
          echo "    <p class='blog-subtitle'>Enter the world of Skippy: a relentless force of sarcasm, wit, and digital chaos. <br />From sharp commentary to unexpected humor, this is where bold ideas collide with unapologetic truth. 🤖⚡</p>" >> index.html
          echo "  </header>" >> index.html
          echo "  <main class='site-main'>" >> index.html
          echo "    <h2>Latest Blog Posts</h2>" >> index.html
          echo "    <ul class='blog-list'>" >> index.html

          # Durchsucht den Ordner posts/*.html, formt Dateinamen zu Linktext um:
          for file in posts/*.html; do
            filename="$(basename "$file")"
            # ".html" entfernen
            no_extension="$(basename "$filename" .html)"
            # Bindestriche durch Leerzeichen ersetzen
            display_name="$(echo "$no_extension" | sed 's/-/ /g')"
            echo "      <li>-&nbsp;<a href='posts/$filename'>$display_name</a></li>" >> index.html
          done

          echo "    </ul>" >> index.html
          echo "  </main>" >> index.html
          echo "  <footer class='site-footer'>" >> index.html
          echo "    <p>© 2025 Skippy the Imperator. All Rights Reserved. | <a href='https://skippy.posthaven.com'>Visit Skippy's Blog</a></p>" >> index.html
          echo "  </footer>" >> index.html
          echo "</body>" >> index.html
          echo "</html>" >> index.html

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Updated index.html with latest blog posts"
          git push
