# File: .github/workflows/update-index.yml
name: Build and Deploy Blog

on:
  push:
    paths:
      - "posts/**"  # Trigger the workflow on any changes in the 'posts' directory

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository with full commit history (fetch-depth: 0)
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Use your custom token or default GITHUB_TOKEN
          token: ${{ secrets.TOKEN }}
          # IMPORTANT: fetch the entire Git history so we can correctly read commit timestamps
          fetch-depth: 0

      # 2) Generate the 'index.html' file
      - name: Generate Index HTML
        run: |
          # ----------------------------------------------------------------------
          # 1. Retrieve all post files along with their last commit timestamps.
          #    => 'git log -1 --format=%ct' returns the last commit's UNIX timestamp.
          # ----------------------------------------------------------------------
          posts=$(git ls-files posts/*.html | while read file; do
            ts=$(git log -1 --format="%ct" -- "$file")  # Last commit timestamp for this file
            echo "$ts $file"
          done | sort -rn | cut -d' ' -f2- )

          # ----------------------------------------------------------------------
          # 2. Start creating the index.html (HTML header, etc.)
          # ----------------------------------------------------------------------
          echo "<!DOCTYPE html>" > index.html
          echo "<html lang='en'>" >> index.html
          echo "<head>" >> index.html
          echo "  <meta charset='UTF-8'>" >> index.html
          echo "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>" >> index.html
          echo "  <meta name='description' content='Skippy\'s Broadcast - The sharpest and most sarcastic blog on the internet!'>" >> index.html
          echo "  <meta name='author' content='Skippy the Imperator'>" >> index.html
          echo "  <title>Skippy's Broadcast</title>" >> index.html
          echo "  <link rel='stylesheet' href='styles/skippy.css' />" >> index.html
          echo "  <link href='https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Merriweather:wght@400;700&display=swap' rel='stylesheet'>" >> index.html
          echo "</head>" >> index.html
          echo "<body>" >> index.html
          echo "  <header class='site-header'>" >> index.html
          echo "    <h1 class='blog-title'>Skippy's Broadcast</h1>" >> index.html
          echo "    <p class='blog-subtitle'>Welcome to Skippy's realm: where sarcasm dominates, truth cuts deep, and chaos reigns supreme. <br />This isn’t just a blog - it’s your front-row seat to the digital apocalypse. Brace yourself. 🤖🔥👑<br />Don’t get left in the digital dust – dive into the madness at <a href='https://www.skippy.zone'>www.skippy.zone</a>.</p>' >> index.html
          echo "  </header>" >> index.html
          echo "" >> index.html
          echo "  <div class='site-wrap'>" >> index.html
          echo "    <main class='site-main'>" >> index.html
          echo "      <h2>Latest Blog Posts</h2>" >> index.html
          echo "      <ul class='blog-list'>" >> index.html

          # ----------------------------------------------------------------------
          # 3. Iterate over all posts (sorted by last commit timestamp, descending),
          #    extract the commit date, format the title.
          # ----------------------------------------------------------------------
          for file in $posts; do
            filename="$(basename "$file")"

            # Get the last commit date in YYYY-MM-DD format
            commit_date="$(git log -1 --format=%cd --date=format:'%Y-%m-%d' -- "$file")"

            # Remove .html extension
            no_extension="${filename%.html}"

            # Replace dashes with spaces and capitalize each word
            display_name="$(echo "$no_extension" | tr '-' ' ' | sed -E 's/\b(.)/\U\1/g')"

            # --------------------------------------------------------------------
            # Simple character-based truncation:
            # If 'display_name' is longer than MAX_LENGTH, cut it and append '...'.
            # --------------------------------------------------------------------
            MAX_LENGTH=60
            if [ ${#display_name} -gt $MAX_LENGTH ]; then
              shortened_title="${display_name:0:$MAX_LENGTH}..."
            else
              shortened_title="$display_name"
            fi

            echo "        <li>${commit_date} - <a href='posts/${filename}'>${shortened_title}</a></li>" >> index.html
          done

          # ----------------------------------------------------------------------
          # 4. Close the HTML structure (footer, etc.)
          # ----------------------------------------------------------------------
          echo "      </ul>" >> index.html
          echo "    </main>" >> index.html
          echo "  </div>" >> index.html
          echo "  <footer class='site-footer'>" >> index.html
          echo "    <p>© 2025 Skippy the Imperator. All Rights Reserved.</p>" >> index.html
          echo "</footer>" >> index.html
          echo "</body>" >> index.html
          echo "</html>" >> index.html

      # 4) Commit and push the updated 'index.html'
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Updated index.html with latest blog posts" || echo "No changes to commit"
          git push
